@startuml "Diagramme de cas d'utilisation"

left to right direction

actor "Utilisateur" as User

actor "Administrateur" as Admin

package "Gestion de compte"{
	usecase "Créer compte commun de dépenses" as cccd
	usecase "Créer compte personnel" as ccp
	usecase "Clôturer un compte commun" as ccc
	usecase "Consulter la liste des comptes communs" as clcc
    usecase "Ajouter un compte bancaire" as acb
}

package "Gestion des participants"{
	usecase "Inviter un participant" as iup
}

package "Gestion des dépenses"{
    usecase "Consulter ses dettes" as csd
    usecase "Régler une partie de sa dette envers quelqu’un" as rpd
}

package "Administration"{
    usecase "Recherche un profil utilisateur" as rpu
    usecase "Consulter un profil utilisateur" as cpu
    usecase "Transférer de l’argent d’un compte à un autre" as tda
}

@enduml