@startuml "Diagramme de contexte statique"

left to right direction

skinparam actor {
BackgroundColor<< externe >> Black
BorderColor<< externe >> Black
StereotypeFontSize<< externe >> 0
}

actor "Utilisateur\n(*)" as User

actor "Administrateur\n(*)" as Admin

actor "Système bancaire\n(1)" << externe >> as SB

rectangle "ShareCount" as SC

User -- SC
Admin -- SC
SB - SC

@enduml