@startuml
actor Administrateur as a
participant ShareCount as sc

a 	-> 	sc : Réinitialiser mot de passe
a 	<-	sc : Etes vous sur ?
alt Annulation
a 	->	sc : Non
a 	<-	sc : Mot de passe inchangé
else
a 	->	sc : Oui
a 	<- 	sc : Saisir mot de passe admin
a 	-> 	sc : Mot de passe admin
sc 	-> 	sc : Vérifier mot de passe
alt Mot de passe admin invalide
a 	<- 	sc : Mot de passe admin invalide veuillez réeesayer
else
a 	<-	sc : Saisir nouveau mot de passe
a 	->	sc : Nouveau mot de passe
a 	<-	sc : Confirmer nouveau mot de passe
a 	->	sc : Nouveau mot de passe
sc 	->	sc : Verifier validité mot de passe
alt Mot de passe non valide
a 	<-	sc : Mot de passe non valide veuillez réessayer
else
sc 	->	sc : Changer mot de passe de l'utilisateur
a 	<-	sc : Le mot de passe a bien été modifié
end
end
end
@enduml