@startuml  Accepter une demande d’ajout

actor utilisateur as u
participant ShareCount as sc

sc -> u : Afficher l'informations sur le compte

alt Refus
u -> sc : Refuser invitation
else

u -> sc : Accepter invitation
sc -> sc : Ajouter l'utilisateur au compte
sc -> sc : Ajouter le compte dans le liste des comptes

sc -> u : Afficher le compte


end



@enduml