@startuml "Consulter un profil utilisateur (admin)"
actor Administrateur as a
participant ShareCount as sc

a 	-> 	sc : rechercher un utilisateur
a 	<- 	sc : entrez le nom d'utilisateur ou l' email
a 	-> 	sc : nom d'utilisateur ou email
a 	-> 	sc : entrez le nom d'utilisateur ou le mail
alt aucun utilisateur ne correspond
a 	<- 	sc : Aucun utilisateur ne correspond à ce nom d'utilisateur ou ce mail
else
a 	<- 	sc : profil de l'utilisateur correspondant
end
@enduml