@startuml "Creer un compte admin"
actor Administrateur as a
participant ShareCount as sc

a 	-> 	sc : Creer un compte admin
a 	<- 	sc : Entrez le prénom
a 	-> 	sc : prénom
a 	<- 	sc : Entrez le nom
a 	-> 	sc : nom
a 	<- 	sc : Entrez l'adresse email
a 	-> 	sc : email
a 	<- 	sc : Entrez le pseudo
a 	-> 	sc : pseudo
sc 	-> 	sc : Vérification des informations

alt Pseudo déjà utilisé
a 	<- 	sc : Le pseudo est déjà attribué veuillez en choisir un autre
else
alt Email déjà utilisé
a 	<- 	sc : L'email est déjà attribué veuillez en choisir un autre
else
sc 	-> 	sc : Génération d'un mot de passe sécurisé pour le compte
sc 	-> 	sc : Enregistrement des informations du compte
a 	<- 	sc : Compte créé
a 	<- 	sc : Mot de passe du compte généré automatiquement
end
end
@enduml