@startuml
actor Administrateur as a
participant ShareCount as sc

a 	-> 	sc : Annuler transaction
sc 	-> 	sc : Recuperation des transactions de l'utilisateur
a 	<- 	sc : Liste des transactions
a 	<- 	sc : Transactions à annuler
a 	-> 	sc : Choix transaction à annuler
a 	<- 	sc : Saisir mot de passe admin
a 	-> 	sc : Mot de passe admin
sc 	-> 	sc : Vérification mot de passe
alt Mot de passe invalide
a 	<- 	sc : Mot de passe invalide veuillez réeesayer
else
sc 	-> 	sc : Suppression transaction du compte commun
sc 	-> 	sc : Recalcul des dettes du compte commun
sc 	-> 	sc : Mise à jour des dettes du compte commun
sc 	-> 	sc : Notification des utilisateurs de l'annulation de la transaction
a 	<- 	sc : Transaction annulé
end
@enduml