@startuml "Rechercher un profil utilisateur (admin)"
actor Administrateur as a
participant ShareCount as sc

a 	-> 	sc : rechercher un utilisateur
a 	<- 	sc : entrez le nom d'utilisateur ou l' email
a 	-> 	sc : nom d'utilisateur ou email
alt aucun utilisateur ne correspond
a 	<- 	sc : Aucun utilisateur ne correspond à ce nom d'utilisateur ou ce mail
else
sc 	-> 	sc : Récuperation profil utilisateur
a 	<- 	sc : profil de l'utilisateur correspondant
end
@enduml