@startuml  Consulter la liste des dépenses/montant de la cagnotte

actor utilisateur as u
participant ShareCount as sc

u -> sc : Récupérer l'information du compte
sc -> u : Afficher l'information du compte
u -> sc : Sélectionner une période
sc -> sc : Vérifier une période

alt Format incorrect
sc -> u : Format incorrect
else

sc -> u : Afficher la liste des dépenses
end

@enduml