@startuml  Consulter la liste des comptes communs

actor utilisateur as u
participant ShareCount as sc

u -> sc : Consulter la liste des comptes communs
sc -> sc : Vérifier la liste des comptes communs

alt Liste vide
sc -> u : Liste des comptes vide
else

sc -> u : Liste des comptes communs auquels l'utilisateur participe

end

@enduml