@startuml  Créer compte personnel

actor utilisateur as u
participant ShareCount as sc

u -> sc : Créer un nouveau compte personnel
sc -> u : Entrez votre prénom
u -> sc : Envoyer le prénom
sc -> u : Entrez votre nom
u -> sc : Envoyer le nom
sc -> u : Entrez votre adresse email
u -> sc : Envoyer l'adresse email
sc -> u : Entrez votre pseudo
u -> sc : Envoyer le pseudo
sc -> u : Entrez votre mot de passe
u -> sc : Envoyer le mot de passe
sc -> sc : Vérifier les informations
sc -> sc : Vérifier l'unicité de l'adresse mail et du pseudo

alt Information non valide
sc -> u : Cette information est non valide
sc -> u : Resaisir l'information non valide
else

alt Information déjà prise
sc -> u : Cette information est déjà prise
sc -> u : Resaisir l'information non disponible
else

sc -> u : Compte créé

end

end

@enduml