@startuml  Inviter/Ajouter un participant

actor utilisateur as u
participant ShareCount as sc

u -> sc : Ajouter un utilisateur à un compte commun
sc -> sc : Vérifier si l'utilisateur existe

alt Utilisateur n'existe pas
sc -> u : utilisateur invalide
else

sc -> sc : Vérifier si l'invitation n'a pas déjà été envoyée

alt Invitation déjà envoyée 
sc -> u : Invitation déjà envoyée
else

sc -> sc : Vérifier si l'utilisateur n'est pas déjà dans le groupe
sc -> sc : Envoie une invitation à l'utilisateur 
sc -> u : Demande d'ajout envoyée

end
end

@enduml