@startuml "Régler une partie de sa dette envers quelqu’un"

actor Utilisateur as u
participant ShareCount as sc
participant ServiceBancaire as sb

u 	-> 	sc : Régler partie dette
u		<- 	sc : Liste des dettes à régler
u		-> 	sc : Sélection des dettes à regler
alt Absence de compte bancaire
sc -> u : Absence de compte bancaire
else
sc -> sb : 
end



@enduml