@startuml  Supprimer son compte admin

actor admin as a
participant ShareCount as sc

a -> sc : Supprimer son compte
sc -> a : Demander confirmation
a -> sc : Confirmer la suppression de compte
sc -> a : Votre compte va être supprimé
sc -> sc : Déconnecter l'utilisateur
sc -> sc : Supprimer la totalité du compte de la base de données

@enduml