@startuml  Créer compte personnel

actor utilisateur as u
participant ShareCount as sc

u -> sc : Supprimer son compte
sc -> u : Demander confirmation
u -> sc : Confirmer la suppression de compte
sc -> u : Votre compte va être supprimé
sc -> sc : Déconnecter l'utilisateur
sc -> sc : Supprimer la totalité du compte de la base de données

@enduml