@startuml  Transférer de l'argent sur son compte

actor utilisateur as u
participant ShareCount as sc

sc -> u : Choisir un compte commun
u -> sc : Ouvrir le compte
sc -> u : Afficher l'information du compte
u -> sc : Demander un transfert d'argent
sc -> sc : Vérification du compte bancaire

alt Absence de compte bancaire
sc -> u : Absence de compte bancaire
else

sc -> u : Demander un motif
u -> sc : Entrer le motif
sc -> u : Demander un montant
u -> sc : Entrer le montant
sc -> sc : Enregistrer le transfert
sc -> sc : Demander la confirmation d'autres utilisateurs
sc -> u : Demande de transfert enregistré

end

@enduml