@startuml Valider la cloture d'un compte

actor utilisateur as u
participant ShareCount as sc


sc -> u : Afficher l'informations sur le compte

u -> sc : Refuser la clôture
alt Refus
sc -> sc : Notifier le demandeur de clôture
sc -> sc : Supprimer les demandes d'autres membres
else

u -> sc : Valider le transfert

alt nb de validation = nb de participants
sc -> sc : Supprimer les demandes
sc -> sc : Notifier les participants
sc -> sc : Fermer le compte

end


end

@enduml