@startuml  Valider une dépense

actor utilisateur as u
participant ShareCount as sc
participant ServiceBancaire as sb

u -> sc : Demander sa liste des notifications
sc -> u : Afficher la liste

alt Aucune demande 
sc -> u : Aucune demande
else

sc -> u : Afficher le demande de validation
u -> sc : Demander l'informations sur le compte
sc -> u : Afficher l'informations sur le compte

alt Refus
u -> sc : Refuser le dépense
sc -> sc : Notifier le demandeur de transfert
else

u -> sc : Valider le dépense

alt nb de validation >=2
sc -> sc : Supprimer les demandes
sc -> sb : Demande de transfert
sb -> sb : Vérifier le demande

alt Erreur bancaire
sb -> sc : Erreur de transfert
sc -> sc : Notifier le demandeur de transfert
else
sb -> sc : Retirer de l'argent
sc -> sc : Modifier le montant du compte
sc -> sc : Notifier le demandeur de transfert

end
end
end
end


@enduml