@startuml  Consulter un compte de dépenses

actor utilisateur as user
participant GestionnaireDialogue as gd
participant BaseDonnees as bd

user 	-> gd 	: Compte de dépenses communes
gd 		-> bd 	: GetDepenses(idCompteDepenses)
user 	<- gd 	: Liste des dépenses du compte affichant le motif,\n la date de la dépense, la somme, les participants concernés ainsi que leur part dans la dépense

@enduml