@startuml Modifier infos personnelles
actor "Client" as user
participant GestionnaireDialogue as gd
participant Utilisateur as u
participant GestionnaireSauvegarde as gs

user -> gd : Modifier ses informations personnelles utilisateur
gd 	-> 	gd : afficherInterfaceModificationInfosPersonnelles()
user 	-> 	gd : prénom
user 	-> 	gd : nom
user 	-> 	gd : mot de passe
user 	-> 	gd : nouveau mot de passe
user 	-> 	gd : confirmation nouveau mot de passe
gd 	-> gd ++: hasher(motDePasse)
gd 	--> gd --: hashMDP
gd 	-> 	gs : verifierInformationsUtilisateur(prenom,nom,hashMDP)
gs 	--> 	gd : retour
alt retour = prenom invalide
user 	<-- 	gd : afficherMessageInformation("Le prénom n'est pas valide, veuillez fournir un prénom valide")
else
alt retour = nom invalide
user 	<-- 	gd : afficherMessageInformation("Le nom n'est pas valide, veuillez fournir un nom valide")
else
gd 	-> gd ++: hasher(motDePasse)
gd 	--> gd --: hashMDP
gd -> gs : combinaisonExiste(pseudo,hashMDP)
gs --> gd : retour
alt retour = false
user 	<-- 	gd : afficherMessageInformation("Ceci n'est pas votre mot de passe veuillez réessayer")
else retour = true
gd 	-> gd ++: hasher(motDePasse)
gd 	--> gd --: hashMDP1
gd 	-> gd ++: hasher(confirmationMotDePasse)
gd 	--> gd --: hashMDP2
gd 	-> 	gd ++: checkNouveauMdp(hashMDP1,hashMDP2)
gd --> gd --: retour 
alt retour = false
user 	<-- 	gd : afficherMessageInformation("Le nouveau mot de passe et la confirmation ne correspondent pas, veuillez réessayer")
else retour = true
gd 	-> 	u : modifierInfosUtilisateur(u)
gd 	-> 	gs : modifierInfosUtilisateur(u)
user 	<-- 	gd : afficherMessageInformation("Vos informations ont bien été sauvegardées")
end
end
end
end
@enduml