@startuml Classes

	class GestionnaireDialogue {
		+void creerCompteUtilisateur(String pseudo, String prenom, String nom, String email, String motDePasse, String confirmationMotDePasse)
		+void creerCompteDepensesCommunes(String nom, String description)
		+void consulterListeCompteDepensesCommunes(CompteUtilisateur compteU)
		+String hasher(String phraseAHasher)
		+void afficherMessageInformation(String message)
		+void afficherMessageErreur(String message)
		+void afficherListeComptesDepensesCommunes(Liste<CompteDepensesCommunes> listeComptesDepenses)
		+boolean pseudoConforme(String pseudo)
		+boolean prenomConforme(String prenom)
		+boolean nomConforme(String nom)
		+boolean emailConforme(String email)
		+boolean motDePasseConforme(String motDePasse)
		+boolean nomCompteConforme(String nom)
		+boolean verifiePseudo(String pseudo, String hash)
		+void seConnecter(String pseudo, String motDePasse)
		+CompteUtilisateur recuperationInformations(String pseudo)
		+void afficherPageAccueil(CompteUtilisateur utilisateur)
	}
	GestionnaireDialogue --"1" CompteUtilisateur
	GestionnaireDialogue --"1" GestionnaireSauvegarde

	class GestionnaireSauvegarde {
		+CompteDepensesCommunes creerCompteDepensesCommunes(CompteUtilisateur compteU, String nom, String description)
		+boolean sauvegarderCompteUtilisateur(CompteUtilisateur compte)
		+boolean pseudoExiste(String pseudo)
		+Liste<CompteDepensesCommunes> getListeComptesDepensesCommunes(CompteUtilisateur cu)
	}

	class CompteUtilisateur {
		String pseudoUtilisateur
		String prenomUtilisateur
		String nomUtilisateur
		String emailUtilisateur
		String hashMotDePasseUtilisateur
		+CompteUtilisateur(String pseudo, String prenom, String nom, String email, String hashMDP)
		+void setComptesDepensesCommunes(Liste<CompteDepensesCommunes> listeComptesDepenses)
		+boolean sauvegarder(GestionnaireSauvegarde gs)
		+boolean addCompteDepenseCommunes(CompteDepensesCommunes cdc)
		+void recupererComptesDepensesCommunes(GestionnaireSauvegarde gs)
		+Liste<CompteDepensesCommunes> getListeComptesDepensesCommunes()
		+String getPseudoUtilisateur()
		+String getPrenomUtilisateur()
		+String getNomUtilisateur()
		+String getEmailUtilisateur()
		+String getHashMotDePasseUtilisateur()
		+String setPseudoUtilisateur(String pseudo)
		+String setPrenomUtilisateur(String prenom)
		+String setNomUtilisateur(String nom)
		+String setEmailUtilisateur(String email)
		+String setHashMotDePasseUtilisateur(String motDePasse)
	}
	CompteUtilisateur --"*" CompteDepensesCommunes
	class CompteDepensesCommunes {
		+CompteDepenseCommunes(String identifiant, CompteUtilisateur compteU, String nom, String description, Date dateCreation)
	}

@enduml