@startuml Classes

	class GestionnaireDialogue {

	}

	class CompteUtilisateur {
		String nomUtilisateur
		String prenomUtilisateur
		String pseudoUtilisateur
		String emailUtilisateur
		String hashMotDePasseUtilisateur
	}
	CompteDepensesCommunes "*"--"*" CompteUtilisateur

	class GestionnaireDialogue {
		CompteUtilisateur u
		GetListeDesComptesDepenses(CompteUtilisateur)
		GetDepenses(CompteUtilisateur, Compte)
		verifierInfosCreationCompteDepense(nom, description)
		afficherInterfaceCreationCompteDepensesCommunes()
		nouveauFormulaire()
		verifierFormulaire(Formulaire)
		modifierInfosUtilisateur(CompteUtilisateur,Formulaire)
		enregistrerNouvelUtilisateur(Formulaire)
	}

	class CompteDepensesCommunes {
		String nomCompteDepenses
		String idCompteDepenses
		Date dateCreationCompteDepenses
		Date dateClotureCompteDepenses
		CompteUtilisateur createurCompteDepenses
	}
	CompteDepensesCommunes "*"--"*" CompteUtilisateur
	GestionnaireDialogue --"*" CompteUtilisateur

@enduml