@startuml Classes

	class GestionnaireDialogue {
		void consulterCompteDepensesCommunes(CompteDepensesCommunes compteDC)
		void consulterListeCompteDepensesCommunes(CompteUtilisateur compteU)
		void afficherListeDepensesCommunes(Collection<Depense> listeDepenses)
		void afficherMessageInformation(String message)
		void afficherMessageErreur(String message)
		void afficherListeComptesDepensesCommunes(Collection<CompteDepensesCommunes> listeComptesDepenses)
		void afficherPageAccueil(CompteUtilisateur compte)
		void creerCompteUtilisateur(String pseudo, String prenom, String nom, String email, String motDePasse, String confirmationMotDePasse)
		void creerCompteDepensesCommunes(String nom, String description)
		void seConnecter(String pseudo, String motDePasse)
		String hasher(String motDePasse)
		bool pseudoConforme(String pseudo)
		bool prenomConforme(String prenom)
		bool nomConforme(String nom)
		bool emailConforme(String email)
		bool motDePasseConforme(String motDePasse)
		bool nomCompteConforme(String nom)
	}
	GestionnaireDialogue --"1" ComptePersonnel
	GestionnaireDialogue --"1" GestionnaireSauvegarde

	interface GestionnaireSauvegarde {
		creerCompteDepensesCommunes(CompteUtilisateur createur, String nom, string description)
		getDepenses(CompteDepensesCommunes compteDC)
		getComptesDepensesCommunes(CompteUtilisateur compteU)
		getCompte(String pseudo)
		bool sauvegarderCompteUtilisateur(CompteUtilisateur compteU)
		bool compteExiste(String pseudo, String hashMDP)
		bool pseudoExiste(String pseudo)
	}

	class GestionnaireSauvegardeFichier implements GestionnaireSauvegarde {

	}

	interface ComptePersonnel {
		String pseudo
		String prenom
		String nom
		String email
		String hashMotDePasse
		ComptePersonnel(String pseudo, String prenom, String nom, String email, String hashMDP);
		bool sauvegarder()
		String getPseudo()
		String getPrenom()
		String getNom()
		String getEmail()
		String getHashMotDePasse()
		void setPseudo(String pseudo)
		void setPrenom(String prenom)
		void setNom(String nom)
		void setEmail(String email)
		void setHashMotDePasse(String hashMDP)
		void setGestionnaireSauvegarde(GestionnaireSauvegarde gs)
	}
	ComptePersonnel --"1" GestionnaireSauvegarde

	class CompteAdministrateur implements ComptePersonnel {
		bool sauvegarder()
	}


	class CompteUtilisateur implements ComptePersonnel {
		bool sauvegarder()
		bool recupererInfosCompteDepensesCommunes(CompteDepensesCommunes compteDC)
		bool recupererComptesDepensesCommunes()
		Collection<CompteDepensesCommunes>  getComptesDepensesCommunes()
		void addCompteDepensesCommunes(CompteDepensesCommunes compteDC)
		void setComptesDepensesCommunes(Collection<CompteDepensesCommunes>listeComptesDepenses)
	}
	CompteUtilisateur "1"--"*" CompteDepensesCommunes

	class CompteDepensesCommunes {
		String identifiant
		String nom
		String description
		Date dateCreation
		CompteDepensesCommunes(String identifiant, String nom, String description, Date dateCreation, CompteUtilisateur createur)
		bool recupererDepenses()
		Collection<Depenses> getDepenses()
		void setDepenses(listeDepenses)
	}
	CompteDepensesCommunes --"*" Depense

	class Depense {

	}

@enduml