@startuml  Consulter la liste de ses comptes de dépenses communes

actor "Utilisateur" as us
participant ":GestionnaireDialogue" as gd
participant "compteU:CompteUtilisateur" as cu
participant "db:GestionnaireSauvegarde" as gs
participant "cd:CompteDepensesCommunes" as cd

us 	-> 	gd 	: consulterListeCompteDepensesCommunes(compteU)
gd 	-> 	cu 	: recupererComptesDepensesCommunes()
cu 	->	gs 	: getComptesDepensesCommunes(this)
loop pour tous les comptes de depenses communes de l'utilisateur
gs 	-> 	cd 	**: CompteDepensesCommunes(identifiant, compteU, nom, description, dateCreation)
cd 	--> gs 	: cd
end
gs 	--> cu 	: listeComptesDepenses
cu 	-> 	cu 	: setComptesDepensesCommunes(listeComptesDepenses)
cu 	--> gd 	: bool recuperés
' TODO Verifier que la récupération a marché avant de continuer
gd 	-> 	cu 	: getComptesDepensesCommunes()
cu 	--> gd 	: listeComptesDepenses
alt listeComptesDepenses != vide
gd 	->	gd 	: afficherListeComptesDepensesCommunes(listeComptesDepenses)
gd 	-->	us 	: listeComptesDepenses
else listeComptesDepenses = vide
gd 	-> 	gd  : afficherMessageInformation("Vous ne participez à aucun compte de dépenses communes")
gd 	-->	us 	:Vous ne participez à aucun compte de dépenses communes
end
@enduml