@startuml  Consulter un compte de dépenses

actor "Utilisateur" as us
participant ":GestionnaireDialogue" as gd
participant "compteU:CompteUtilisateur" as cu
participant "compteDC:CompteDepensesCommunes" as cd
participant "db:GestionnaireSauvegarde" as gs

us 	-> 	gd 	: consulterCompteDepensesCommunes(compteDC)
gd 	-> 	cu 	: recupererInfosCompteDepensesCommunes(compteDC)
cu 	-> cd 	: recupererDepenses()
cd 	->	gs 	: getDepenses(this)
gs 	--> cd 	: listeDepenses
cd 	-> 	cd 	: setDepenses(listeDepenses)
cd 	--> cu 	: bool recuperé
cu 	--> gd 	: bool recuperé
alt retour=true
' TODO Verifier que la récupération a marché avant de continuer
gd 	-> 	cd 	: getDepenses()
cd 	--> gd 	: listeDepenses
alt ComptesDepenses != vide
gd 	->	gd 	: afficherListeDepensesCommunes(listeDepenses)
gd 	-->	us 	: listeDepenses
else ComptesDepenses = vide
gd 	-> 	gd  : afficherMessageInformation("Vous ne participez à ce compte de dépenses communes")
gd 	-->	us 	: Vous ne participez à ce compte de dépenses communes
end
else retour!=true
gd -> gd : afficherMessageErreur(Erreur de récupération pour le compte sélectionné);
gd -> us : Erreur de récupération pour le compte sélectionné
end
@enduml