@startuml  Consulter la liste de ses comptes de dépenses communes

actor "Utilisateur" as us
participant ":GestionnaireDialogue" as gd
participant "compteU:CompteUtilisateur" as cu
participant "db:GestionnaireSauvegarde" as gs

us 	-> 	gd 	: consulterListeCompteDepensesCommunes(compteU)
gd 	-> 	cu 	: getComptesDepensesCommunes(gs)
cu 	->	gs 	: getListeComptesDepensesCommunes(cu)
gs 	--> cu 	: listeComptesDepenses
cu 	-> 	cu 	: setComptesDepensesCommunes(listeComptesDepenses)
cu 	--> gd 	:
gd 	-> 	cu 	: getListeComptesDepensesCommunes()
cu 	--> gd 	: listeComptesDepenses
alt listeComptesDepenses != vide
gd 	->	gd 	: afficherListeComptesDepensesCommunes(listeComptesDepenses)
gd 	-->	us 	: listeComptesDepenses
else listeComptesDepenses = vide
gd 	-> 	gd  : afficherMessageInformation("Vous ne participez à aucun compte de dépenses communes")
gd 	-->	us 	:Vous ne participez à aucun compte de dépenses communes
end
@enduml