@startuml  Consulter la liste de ses comptes de dépenses communes

actor utilisateur as user
participant GestionnaireDialogue as gd

user -> gd 	: Consulter la liste de ses comptes de dépenses communes
gd -> gd 	: GetListeDesComptesDepenses(Utilisateur)

alt Liste vide
gd -> user  : Vous ne participez à aucun compte de dépenses communes
else
gd -> user  : Liste des comptes de dépenses communes auxquels l'utilisateur participe en \naffichant pour chacun Le nom, l'id, la date de creation,\n la date de cloture si elle est cloturée et le\n pseudo du createur du compte

end

@enduml