@startuml
actor "Utilisateur" as user
participant GestionnaireDialogue as sc

user 	-> 	sc : Creer un compte utilisateur
sc 	-> 	sc : f = nouveauFormulaire()
user 	-> 	sc : prénom
user 	-> 	sc : nom
user 	-> 	sc : email
user 	-> 	sc : pseudo
user 	-> 	sc : mot de passe
user 	-> 	sc : confirmation mot de passe
sc 	-> 	sc : verifierFormulaire(f)
alt Prénom non valide
user 	<- 	sc : Le prénom n'est pas valide, veuillez fournir un prénom valide
else
alt Nom non valide
user 	<- 	sc : Le nom n'est pas valide, veuillez fournir un nom valide
else
alt Pseudo déjà utilisé
user 	<- 	sc : Le pseudo est déjà attribué veuillez en choisir un autre
else
alt Email déjà utilisé
user 	<- 	sc : L'email est déjà attribué veuillez en choisir un autre
else
alt Le mot de passe n'est pas sécurisé
user 	<- 	sc : Le mot de passe n'est pas sécurisé, veuillez réessayer
else
alt Les mot de passe ne sont pas les même
user 	<- 	sc : Le mot de passe et la confirmation ne correspondent pas, veuillez réessayer
else
sc 	-> 	sc : enregistrerNouvelUtilisateur(f)
user 	<- 	sc : Compte créé
end
end
end
end
end
end
@enduml