@startuml  Creer un compte de dépenses communes

actor "Utilisateur" as us
participant ":GestionnaireDialogue" as gd
participant "compteU:CompteUtilisateur" as cu
participant "db:GestionnaireSauvegarde" as gs
participant "cdc:CompteDepensesCommunes" as cdc

us 	-> 	gd : creerCompteDepensesCommunes(nom, description)
' verification du nom
gd 	-> 	gd ++: nomCompteConforme(nom)
gd 	--> 	gd --: retour
alt retour = true
gd 	-> 	gs : creerCompteDepensesCommunes(compteU, nom, description)
gs 	-> 	cdc **: CompteDepenseCommunes(identifiant, compteU, nom, description, dateCreation)
cdc --> gs : cdc
gs --> 	gd : cdc
alt cdc != vide
gd -> 	cu : addCompteDepenseCommunes(cdc)
cu 	--> gd :
ref over gd : consulter son compte utilisateur
else cdc = vide
gd 	-> 	gd 	: afficherMessageErreur("Impossible de créer le compte de dépense")
gd 	--> 	us : Impossible de créer le compte de dépense
end
else retour = false
gd 	-> 	gd : afficherMessageErreur("Le nom de compte n'est pas valide")
gd 	--> 	us : Le nom de compte n'est pas valide
end
@enduml