@startuml  Creer un compte de dépenses communes

actor Client as client
participant GestionnaireDialogue as gd
participant Utilisateur as user
participant CompteDepensesCommunes as cdc
participant BaseDonnees as bd

client 	-> gd 		: Creer un compte de dépenses communes
gd 		-> gd 	: afficherInterfaceCreationCompteDepensesCommunes()
client 	<- gd 		: Saisir le nom du compte
client 	-> gd 		: Nom
client 	<- gd 		: Saisir la description du compte
client 	-> gd 		: Description
gd 		-> gd 		: verifierInfosCreationCompteDepense(nom, description)
alt Nom invalide
client 	<- gd 		: Le nom du compte est invalide
else
gd 		-> user 		: compte = creerCompteDepensesCommunes(nom, description)
user 		-> cdc 		: c = new CompteDepensesCommunes(nom, description, this)
user 		-> cdc 		: sauvegarder()
cdc 		-> bd 		: enregistrerCompteDepensesCommunes(this)
client 	<- gd 		: Le compte a été crée
gd 	-> gd 		: afficherInterfaceCompteDepensesCommunes(compte)
end
@enduml