@startuml
actor "Utilisateur" as user
participant GestionnaireDialogue as sc

user -> sc : Modifier ses informations personnelles utilisateur
sc 	-> 	sc : u = getUtilisateur(Utilisateur)
sc 	-> 	sc : f = nouveauFormulaire()
user 	-> 	sc : prénom
user 	-> 	sc : nom
user 	-> 	sc : mot de passe
user 	-> 	sc : nouveau mot de passe
user 	-> 	sc : confirmation nouveau mot de passe
sc 	-> 	sc : verifierFormulaire(f)
alt Prénom non valide
user 	<- 	sc : Le prénom n'est pas valide, veuillez fournir un prénom valide
else
sc 	-> 	sc : Conservation de l'ancien prénom si le champ est vide
alt Nom non valide
user 	<- 	sc : Le nom n'est pas valide, veuillez fournir un nom valide
else
sc 	-> 	sc : Conservation de l'ancien nom si le champ est vide
sc 	->	sc : Comparaison du hash du mot de passe avec celui du mot de passe stocké
alt Les hash ne correspondent pas
user 	<- 	sc : Ceci n'est pas votre mot de passe veuillez réessayer
else
sc 	-> 	sc : Comparaison du nouveau mot de passe et de la confirmation
alt Les mot de passe ne sont pas les même
user 	<- 	sc : Le nouveau mot de passe et la confirmation ne correspondent pas, veuillez réessayer
else
sc 	-> 	sc : modifierInfosUtilisateur(u,f)
user 	<- 	sc : Vos informations ont bien été sauvegardées
end
end
end
end
@enduml