@startuml Se connecter ou créer son compte

actor "Utilisateur" as us
participant "GestionnaireDialogue" as gd
participant "db:GestionnaireSauvegarde" as gs
participant "CompteUtilisateur" as cu
participant "CompteAdministrateur" as ca

us -> gd : seConnecter(pseudo,motDePasse)
gd 	-> gd ++: hasher(motDePasse)
gd 	--> gd --: hashMDP
gd -> gs : compteExiste(pseudo,hashMDP)
gs --> gd : retour

alt retour = false
gd --> us : afficherMessageInformation("Pseudo ou mot de passe incorrect, veuillez les ré entrer")
else retour = true

gd -> gs : getCompte(pseudo)

alt Identifiant correspond à un utilisateur
gs -> cu **: CompteUtilisateur(pseudo, prenom, nom, email, hashMDP)
cu --> gs : compte
gs -> cu 	: setGestionnaireSauvegarde(this)
cu --> gs 	:
else Identifiant correspond à un administrateur
gs -> ca **: CompteAdministrateur(pseudo, prenom, nom, email, hashMDP)
ca --> gs : compte
gs -> ca 	: setGestionnaireSauvegarde(this)
ca --> gs 	:
end
gs --> gd : compte
gd --> gd : afficherPageAccueil(compte)

end


@enduml