@startuml Se connecter ou créer son compte

actor "Utilisateur" as us
participant "GestionnaireDialogue" as gd
participant "db:GestionnaireSauvegarde" as gs

alt Création de compte

us -> gd : Creer un compte
ref over gd : Creer un compte utilisateur
else Connexion

us -> gd : seConnecter(pseudo,motDePasse)
gd 	-> gd ++: hasher(motDePasse)
gd 	--> gd --: hashMDP
gd -> gs : verifiePseudo(pseudo,hashMDP)
gs --> gd : retour

alt Informations incorrectes
gd --> us : afficherMessageInformation("Pseudo ou mot de passe incorrect, veuillez les ré entrer")
else

gd -> gs : recuperationInformations(pseudo)
gs --> gd : compteUtilisateur

alt Identifiant correspond à un utilisateur
gd --> us : afficherPageAccueil(compteUtilisateur)
else Identifiant correspond à un administrateur

gd --> us : afficherPageAccueil(compteUtilisateur)

end

end

end

@enduml