@startuml  Valider un transfert d’argent

actor utilisateur as u
participant ShareCount as sc
participant ServiceBancaire as sb

sc -> u : Afficher l'informations sur le compte

u -> sc : Refuser le transfert
alt Refus
sc -> sc : Notifier le demandeur de transfert
else

u -> sc : Valider le transfert

alt nb de validation >=2
sc -> sc : Supprimer les demandes
sc -> sb : Demande de transfert
sb -> sb : Vérifier le demande

alt Erreur bancaire
sb -> sc : Erreur de transfert
sc -> sc : Notifier le demandeur de transfert
else
sb -> sc : Transférer de l'argent
sc -> sc : Modifier le montant du compte
sc -> sc : Notifier les participants


end
end
end


@enduml