@startuml  Valider la clôture d'un compte de dépense communes

actor utilisateur as u
participant ShareCount as sc

sc -> u : Afficher l'informations sur le compte

u -> sc : Refuser la clôture
alt Refus
sc -> sc : Notifier le créateur du compte
sc -> sc : Modifier le nombre de votes
sc -> u : Votre vote a été pris en compte
else
sc -> sc : Notifier le demandeur de retrait
sc -> sc : Modifier le nombre de votes
sc -> u : Votre vote a été pris en compte

alt nb de validation >= 50% des participants
sc -> sc : Supprimer les notification
sc -> sc : Marquer les utilisateurs comme supprimés
sc -> sc : Interdire aux utilisateur toutes les actions dans le compte
sc -> sc : Marquer le compte comme fermés dans la liste des comptes d'utilisateurs
sc -> sc : Notifier les utilisateurs de compte

end
end


@enduml