@startuml Administration

actor "Administrateur" as admin

package "administration" {
	usecase "Consulter un profil utilisateur" as cpu
	usecase "Consulter une cagnotte" as ccag
	usecase "Consulter les transactions d’une cagnotte" as ctc
	usecase "Annuler une transaction d’une cagnotte" as atc
	usecase "Consulter les participants d'une cagnotte" as cpc
	usecase "Modifier les informations d'un utilisateur" as miu
	usecase "Supprimer un compte d'utilisateur" as scu
}
' appartenance
	admin	--	cpu
	admin	--	ccag
	admin	--	ctc
	admin	-	cpc
	admin	-	miu
	admin	-	scu
	admin	-	atc
'	includes
	cpu	<|.. miu	: <<include>>
	cpu	<|.. scu	: <<include>>
	ccag	<|.. ctc	: <<include>>
	ccag	<|.. cpc	: <<include>>
	ccag	<|.. atc	: <<include>>

@enduml