@startuml Administration

actor "Administrateur" as admin

package "administration" {
	usecase "Annuler une transaction d’une cagnotte" as atc
	usecase "Consulter une cagnotte" as ccag
	usecase "Consulter les participants d'une cagnotte" as cpc
	usecase "Consulter un profil utilisateur" as cpu
	usecase "Modifier les informations d'un utilisateur" as miu
	usecase "Supprimer un compte d'utilisateur" as scu
}
' appartenance
	admin	--	cpu
	admin	--	ccag
	admin	-	cpc
	admin	-	miu
	admin	-	scu
	admin	-	atc
'	includes
	cpu	<|.. miu	: <<include>>
	cpu	<|.. scu	: <<include>>
	ccag	<|.. cpc	: <<include>>
	ccag	<|.. atc	: <<include>>

@enduml