@startuml Cas utilisation
left to right direction

!include gestion-compte-personnel.puml
!include administration.puml
!include notifications.puml
!include cagnotte.puml
!include compte-depenses-communes.puml
@enduml
