@startuml Cas utilisation - Gestion des dépenses
left to right direction

actor "Utilisateur" as User

actor "Administrateur" as Admin

package "Gestion des dépenses"{
        usecase "Enregistrer une dépense" as eud
        usecase "Consulter la liste des dépenses/montant de la cagnotte" as cllddmdlc
        usecase "Transférer de l'argent sur son compte" as tdassc
        usecase "Valider un transfert d’argent" as vuta
        usecase "Valider une dépense" as vud
        usecase "Consulter ses dettes" as csd
				clcc <|.. csd : <<Include>>
        usecase "Régler une partie de sa dette" as rpd
				csd <|.. rpd : <<Include>>
}

User --> eud
User --> cllddmdlc
User --> tdassc
User --> vuta
User --> vud
User --> csd
User --> rpd

clcc <|.. eud : <<include>>

@enduml