@startuml Cas utilisation - Administration
left to right direction

actor "Administrateur" as Admin

package "Administration"{
    usecase "Recherche un profil utilisateur" as rpu
    usecase "Afficher les transactions d’un profil utilisateur" as atpu
    usecase "Annuler une transaction d’un utilisateur" as atu
		usecase "Réinitialiser le mot de passe d’un utilisateur" as rmpu
		usecase "Creer un compte admin" as cca
		usecase "Modifier son mot de passe admin" as mmpa
}

actor "Administrateur" as Admin

Admin --> rpu
Admin --> atpu
Admin --> atu
Admin --> rmpu
Admin --> cca
Admin --> mmpa

atpu <|.. atu  : <<include>>
rpu <|.. atpu  : <<include>>
rpu <|.. rmpu  : <<include>>
@enduml