@startuml Cas utilisation - Gestion de compte
left to right direction

actor "Utilisateur" as User

actor "Administrateur" as Admin

package "Gestion de compte"{
	usecase "Créer compte commun de dépenses" as cccd
	usecase "Créer compte personnel" as ccp
	usecase "Clôturer un compte commun" as ccc
	usecase "Consulter la liste des comptes communs" as clcc
	usecase "Ajouter un compte bancaire" as acb
	usecase "Modifier ses infos personnelles" as msip
	usecase "Supprimer son compte" as ssc
}

User --> cccd
User --> msip
User --> ssc
User --> ccp
User --> ccc
User --> clcc
User --> acb

@enduml