@startuml Cas utilisation - Gestion des participants
left to right direction

actor "Utilisateur" as User

actor "Administrateur" as Admin

package "Gestion des participants"{
	usecase "Inviter un participant" as iup
}

User --> iup

clcc <|.. iup : <<Include>>

@enduml