@startuml  Creer un compte utilisateur

actor "Utilisateur" as user
participant ShareCount as sc

user 	-> 	sc : Creer un compte utilisateur
user 	<- 	sc : Entrez le prénom
user 	-> 	sc : prénom
user 	<- 	sc : Entrez le nom
user 	-> 	sc : nom
user 	<- 	sc : Entrez l'adresse email
user 	-> 	sc : email
user 	<- 	sc : Entrez le pseudo
user 	-> 	sc : pseudo
user 	<- 	sc : Entrez le mot de passe
user 	-> 	sc : mot de passe
user 	<- 	sc : Entrez la confirmation du mot de passe
user 	-> 	sc : confirmation mot de passe
sc 	-> 	sc : Vérification des informations
' verification du pseudo
sc 	-> sc : verification de l'existence du pseudo
alt le pseudo n'existe pas encore
sc 	-> 	sc : verification de la conformite du pseudo
alt le pseudo est conforme
' verification du prénom
sc 	-> 	sc : verification de la conformite du prenom
alt le prenom est conforme
' verification du nom
sc 	-> 	sc : verification de la conformite du nom
alt le nom est conforme
' verification de l'email
sc 	-> 	sc : verification de la conformite de l'email
alt l'email est conforme
' verification du mot de passe
sc 	-> 	sc : verification de la conformite du mot de passe
alt le mot de passe est conforme
alt le mot de passe et la confirmation du mot de passe correspondent
sc -> sc : hashage du motDePasse
sc --> sc : enregistrement du compte de l'utilisateur avec le hash du mot de passe à la place du mot de passe
alt enregistrement reussi
sc 	--> 	user : Le compte a été créé
ref over sc : consulter compte d'utilisateur
else
sc 	--> 	user : Le compte n'a pas été sauvegardé
end
else
sc 	--> 	user : Les mots de passe ne correspondent pas
end
else
sc 	--> 	user : Le mot de passe n'est pas valide
end
else
sc 	--> 	user : L'email n'est pas valide
end
else
sc 	--> 	user : Le nom n'est pas valide
end
else
sc 	--> 	user : Le prénom n'est pas valide
end
else
sc 	--> 	user : Le pseudo n'est pas valide
end
else
sc 	--> 	user : Ce pseudo est déjà utilisé
end
@enduml

@enduml