@startuml Classes

	class Utilisateur {
		String nom
		String prenom
		String pseudo
		String email
		String hashMotDePasse
	}

	class Administrateur {
		String nom
		String prenom
		String pseudo
		String email
		String hashMotDePasse
	}

	class Cagnotte {
		Date dateCreation
		Date dateCloture
		String id
		float montantTotal
		Utilisateur createur
	}

	Cagnotte "*"--"*" Utilisateur
	Cagnotte --"*" Transaction

	class CompteDepensesCommunes {
		Date dateCreation
		Date dateCloture
		String id
		Utilisateur createur
	}
	CompteDepensesCommunes "*"--"*" Utilisateur
	CompteDepensesCommunes --"*" Depense

	class Depense {
		String description
		Date dateDeCreation
	}
	Depense --"*" Dette

	class Dette {
		float somme
		float sommeReglee
	}
	Dette --"2" Utilisateur

	class Transaction {

	}

	Transaction --"2" CompteBancaire

	class CompteBancaire {

	}

	class NotificationSimple {

	}

	class NotificationAValider {

	}

	class DemandeRetraitArgent {
		int nb_votes
		int nb_votes_positifs
		Utilisateur utilisateur_beneficiaire
		double montant
		String motif
	}
	DemandeRetraitArgent --"1" CompteDepensesCommunes

@enduml