@startuml
	class Utilisateur {
		String nom
		String prenom
		String pseudo
		String email
		String hashMotDePasse
	}

	class Administrateur {
		String nom
		String prenom
		String pseudo
		String email
		String hashMotDePasse
	}

	class Cagnotte {
		Date dateCreation
		Date dateCloture
		boolean cloture
		float montantTotal
		Utilisateur createur
	}

	Cagnotte "*"--"*" Utilisateur
	Cagnotte --"*" Transaction

	class CompteDette {
		Date dateCreation
		Date dateCloture
		boolean cloture
		Utilisateur createur
	}
	CompteDette "*"--"*" Utilisateur
	CompteDette --"*" Depense

	class Depense {
		String description
		Date dateDeCreation
	}
	Depense --"*" Dette

	class Dette {
		float somme
		float sommeReglee
	}
	Dette --"2" Utilisateur

	class Transaction {

	}

	Transaction --"2" CompteBancaire

	class CompteBancaire {

	}

	class NotificationSimple {

	}

	class NotificationAValider {

	}

@enduml