@startuml Classes

	class User {
		String nomUtilisateur
		String prenomUtilisateur
		String pseudoUtilisateur
		String emailUtilisateur
		String hashMotDePasseUtilisateur
	}
	User --"1" CompteBancaire
	class Admin {
		String nomAdmin
		String prenomAdmin
		String pseudoAdmin
		String emailAdmin
		String hashMotDePasseAdmin
	}

	class Cagnotte {
		Date dateCreationCagnotte
		Date dateClotureCagnotte
		String idCagnotte
		float montantCagnotte
		User createurCagnotte
	}

	Cagnotte "*"--"*" User
	Cagnotte --"*" Transaction

	class CompteDepensesCommunes {
		String nomCompteDepenses
		String idCompteDepenses
		Date dateCreationCompteDepenses
		Date dateClotureCompteDepenses
		User createurCompteDepenses
	}
	CompteDepensesCommunes "*"--"*" User
	CompteDepensesCommunes --"*" Depense
	CompteDepensesCommunes --"*" Dette

	class Depense {
		String motifDepense
		float sommeDepense
		Date dateDeCreationDepense
		User createurDepense
	}
	Depense --"*" PartDepense

	class PartDepense {
		float pourcentageDepense
	}
	PartDepense --"1" User

	class Dette {
		float sommeDu
	}
	Dette --"2" User

	class Transaction {
		String idTransaction
		String motifTranscation
		float sommeTransaction
		Date dateDeCreationTransaction
		Date dateAnnulationTransaction
		String typeTransaction
	}

	Transaction --"1" User

	class CompteBancaire {

	}

	class NotificationSimple {

	}

	class NotificationAValider {

	}

	User --"*" NotificationAValider
	User --"*" NotificationSimple

	class DemandeRetraitArgent {
		int nb_votes
		int nb_votes_positifs
		User beneficiaireDemande
		double montantRetrait
		String motif
	}
	DemandeRetraitArgent "*"-- Cagnotte

@enduml