@startuml  Clôturer un compte commun

actor utilisateur as u
participant ShareCount as sc

sc -> u : Choisir un compte commun
u -> sc : Ouvrir le compte
sc -> u : Afficher l'information du compte
u -> sc : Clôturer un compte commun
sc -> sc : Vérifier s'il reste de l'argent

alt Conditions pas réunies
sc -> u : Impossible de supprimer le compte
else

sc -> sc : Demander la confirmation d'autres utilisateurs
sc -> u : Demande de suppression enregistré


end

@enduml