@startuml  Clôturer un compte de dépense communes

actor Utilisateur as user
participant ShareCount as sc
'juste le créateur peut cloturer
' Les compte déjà clôturés ne peuvent pas être sélectionné
user 	-> sc 		: Clôturer compte de dépense communes
sc 	->	sc : verification que l'utlisateur est le createur du compte de dépense communes
alt L'utlisateur n'est pas le créateur
user <- sc : Vous ne pouvez pas clôturer le compte vous n'êtes\n pas le créateur
else
user 	<- sc 		: Saisir le motif de la clôture
user 	-> sc 	: Motif
user 	<- 	sc : Entrez le mot de passe
user 	-> 	sc : mot de passe
sc 	->	sc : Comparaison du hash du mot de passe avec celui du mot de passe stocké
alt Les hash ne correspondent pas
user 	<- 	sc : Ceci n'est pas votre mot de passe veuillez réessayer
else
user 	<- 	sc	: Confirmer la clôture du compte
alt Annulation
user -> sc : Annuler la clôture du compte
sc -> user : Le compte n'a pas été supprimé
else
user -> sc 			: Confirmer clôture
sc -> sc 				: Envoie demande de clôture du compte aux autres participants\n avec le motif de fermeture
user 	<- sc 		: La demande de clôture a été envoyé aux autres participants
end
end
end
@enduml