@startuml  Consulter une cagnotte

actor utilisateur as user
participant ShareCount as sc

user 	-> sc 		: Cagnotte
sc 		-> sc 		: Récuperation transactions de la cagnotte
user 	<- sc 		: Liste des transactions de la cagnotte affichant le motif,\n la date de la transaction, la somme, le participant concerné et si c'est un\n retrait ou un ajout, en grisant les transactions annulées

@enduml