@startuml  "Consulter ses dettes"

actor utilisateur as u
participant ShareCount as sc

u -> sc : Consulter ses dûs
sc 	->	sc : récuperation de toutes les dettes que l'utilisateur doit aux autres participants
u 	<-	sc : Liste des dettes

@enduml