@startuml  Creer un compte de dépenses communes

actor utilisateur as user
participant ShareCount as sc

user 	-> sc 		: Creer un compte de dépenses communes
user 	<- sc 		: Saisir le nom du compte
user 	-> sc 		: Nom
user 	<- sc 		: Saisir la description du compte
user 	-> sc 		: Description
sc -> sc : verification conformite du nom de compte
alt Nom de compte conforme
sc 		-> sc 		: Creation et enregistrement du compte avec un id unique \n et la date de creation
sc 		-> sc 		: Enregistrement de l'utilisateur comme le créateur du compte
user 	<-- sc 		: Le compte a été crée
user 	<-- sc 		: Affichage du compte
else
sc 	--> 	user : Le nom de compte n'est pas valide
end

@enduml