@startuml  "Consulter ses dûs"

actor utilisateur as u
participant ShareCount as sc
'Losrque les remboursements sont validés les dettes sont mis a jour

u -> sc : Consulter ses dûs
sc 	->	sc : récuperation de toutes les dettes de l'utilisateur
u 	<-	sc : Liste des dettes

@enduml